name: Test pull request action 2

on:
  pull_request:
    #branches: [ main ]
  workflow_dispatch:
jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref}}
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REF_NAME