name: Test action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  MY_ENV: Monday
  SOMETHING: something somethang
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - name: Test github.head_ref
        run: echo ${{ github.head_ref}}
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REF_NAME
        
      - name: printout GITHUB_ENV
        env:
          STEP_ENV: step env
        run: echo $GITHUB_ENV
      - name: Test env in parent action
        run: echo $MY_ENV
      - uses: actions/checkout@v2
      - name: Test action in this repo
        uses: ./  # custom action must be named action.yaml. Give a path to action to invoke action.
      
