name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test action in this repo
        uses: ./
