name: Test action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  MY_ENV: Monday
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - name: Test env in parent action
        run: echo $MY_ENV
      - uses: actions/checkout@v2
      - name: Test action in this repo
        uses: ./  # custom action must be named action.yaml. Give a path to action to invoke action.
      
