name: Test action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env:
  MY_ENV: Monday
  SOMETHING: something somethang
  ENVI: tuesday
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - name: Test github.head_ref
        run: echo ${{ github.head_ref}}
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REF_NAME
        
      - name: printout step specific env
        env:
          STEP_ENV: step env
        run: echo $STEP_ENV
      - name: Test env in parent action
        run: echo $MY_ENV
      - uses: actions/checkout@v2
      - name: Test action in this repo
        id: test-action-in-this-repo
        uses: ./  # custom action must be named action.yaml. Give a path to action to invoke action.
      - name: set global env
        run: echo FOO="hello world" >> $GITHUB_ENV        
      - name: get global env
        run: echo $FOO      
      - run: MY_ENV=tuesday
      - run: |
          echo $MY_ENV
          BAR=bar
      - run: echo MY_ENV=Friday >> $GITHUB_ENV
      - run: echo $BAR
      - run: echo $MY_ENV
      - name: Custom action output
        run: echo ${{ steps.test-action-in-this-repo.outputs.random-number}}
  job2:
    needs: [ job1 ]
    runs-on: ubuntu-latest
    steps:
      - name: Does FOO exist?
        run: echo $FOO
      - name: Access env vars
        env:
          TTT: tuomas
        run: echo ${{ env.TTT }}

      - name: Test if
        if: env.ENVI == 'tuesday'
        run: |
          echo day is monday

      - name: Define image meta      
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: something/something/something
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=sha-${{ github.sha }}
            type=raw,value=${{ github.sha }}-${{ github.sha }}-${{ github.sha }}-${{ github.sha }}-${{ github.sha }}-${{ github.sha }}-${{ github.sha }}
          labels: |
            org.opencontainers.image.authors=SoSe/Viihde
            org.opencontainers.image.vendor=Elisa

      - name: Print outputs
        shell: bash
        run: echo "${{ steps.docker_meta.outputs.tags }}"
